# Generated by Django 5.0.7 on 2024-07-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('species', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('watering_frequency', models.IntegerField()),
            ],
        ),
    ]
