# Generated by Django 5.0.7 on 2024-07-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
