# Generated by Django 5.0.7 on 2024-07-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_plant_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
